[tool.poetry]
name = "dronefly-cli"
version = "0.2.0"
description = "Dronefly command-line interface"
authors = ["Ben Armstrong <synrg@debian.org>"]
license = "AGPL-3.0-or-later"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8.1,<3.10"
dronefly-core = { git = "https://github.com/dronefly-garden/dronefly-core" }
rich = "^13.2"

[tool.poetry.dev-dependencies]
black = "^21.8-beta.0"
pytest = "^6.2.5"
pytest-mock = "^3.6.1"
pylint = "^2.10.2"
pytest-asyncio = "^0.16.0"
pre-commit = "^2.18.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
